name: CI

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Create database
        run: |
          sudo systemctl start mysql
          mysql  -u root -proot -e 'CREATE DATABASE IF NOT EXISTS laravel_test;'

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Run tests
        run: ./vendor/bin/pest
        env:
          DB_DATABASE: laravel_test
          DB_PASSWORD: root

  # deploy:
  #   needs: tests
  #   if: ${{ github.ref == 'refs/heads/main' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Setup PHP
  #       uses: shivammathur/setup-php@v2
  #       with:
  #         php-version: 8.1
  #         tools: composer:v2
  #         coverage: none

  #     - name: Require Vapor CLI
  #       run: composer global require laravel/vapor-cli

  #     - name: Install Project Dependencies
  #       run: composer install --no-interaction --prefer-dist --optimize-autoloader

  #     - name: Deploy Environment
  #       if: ${{ github.ref == 'refs/heads/main' }}
  #       run: vapor deploy production
  #       env:
  #         VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}